FROM metabase/metabase:v0.48.3

ADD --chmod=644 https://github.com/ClickHouse/metabase-clickhouse-driver/releases/download/1.3.4/clickhouse.metabase-driver.jar /plugins/clickhouse.metabase-driver.jar
